apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: node-exporter
spec:
  generators:
    - clusters: {} # Automatically use all clusters defined within Argo CD
  template:
    metadata:
      name: "{{cluster}}-node-exporter"
      namespace: argo-cd
    spec:
      project: default
      source:
        repoURL: https://prometheus-community.github.io/helm-charts
        chart: prometheus-node-exporter
        targetRevision: 4.3.0
      destination:
        server: "{{cluster.server}}"
        namespace: node-exporter
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
