apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: podinfo
  namespace: argo-cd
spec:
  generators:
    - git:
        repoURL: https://github.com/gigawhat/argocd-app-sets-v2.git
        revision: HEAD
        files:
          - path: clusters/**/config.yaml
  template:
    metadata:
      name: "{{cluster.name}}-podinfo"
      namespace: argo-cd
    spec:
      project: default
      source:
        repoURL: https://stefanprodan.github.io/podinfo
        chart: podinfo
        targetRevision: "{{ podinfo.chartVersion }}"
        helm:
          valueFiles:
            - "clusters/{{cluster.name}}/values-podinfo.yaml"
      destination:
        server: "{{cluster.server}}"
        namespace: podinfo
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
